# Generated by Django 5.0.1 on 2024-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='form_project/my_data'),
        ),
    ]
